jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: ${JENKINS_ADMIN_ID}
         password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  remotingSecurity:
    enabled: true
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
  globaljobdslsecurityconfiguration:
    useScriptSecurity: true
unclassified:
  location:
    url: http://localhost:8080/
jobs:
  - script: >
      pipelineJob('tsunami-scanner') {
        definition {
          cpsScm {
              scm {
                 git {
                    remote{
                         github("arieldiner/gloat", "https")
                    }
                    branch("*/main")
                 }			
              }
          scriptPath("Jenkinsfile")		
          }
        }
      }


